app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'welcomes#index'

  resources :job_roles
  resources :workspaces
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '*unmatched', to: 'application#send_error_info', via: :all
end

app/app/models/job_role.rb
class JobRole < ApplicationRecord
    has_many :person
end

app/app/controllers/job_roles_controller.rb
class JobRolesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_adm?
  before_action :set_job_role, only: %i[ show edit update destroy ]

  # GET /job_roles or /job_roles.json
  def index
    @job_roles = JobRole.all
  end

  # GET /job_roles/1 or /job_roles/1.json
  def show
  end

  # GET /job_roles/new
  def new
    @job_role = JobRole.new
  end

  # GET /job_roles/1/edit
  def edit
  end

  # POST /job_roles or /job_roles.json
  def create
    @job_role = JobRole.new(job_role_params)

    respond_to do |format|
      if @job_role.save
        format.html { redirect_to @job_role, notice: "Job role was successfully created." }
        format.json { render :show, status: :created, location: @job_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_roles/1 or /job_roles/1.json
  def update
    respond_to do |format|
      if @job_role.update(job_role_params)
        format.html { redirect_to @job_role, notice: "Job role was successfully updated." }
        format.json { render :show, status: :ok, location: @job_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_roles/1 or /job_roles/1.json
  def destroy
    @job_role.destroy
    respond_to do |format|
      format.html { redirect_to job_roles_url, notice: "Job role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_role
      @job_role = JobRole.find_by(id: params[:id])
      self.send_error_info unless @job_role.present?
    end

    # Only allow a list of trusted parameters through.
    def job_role_params
      params.require(:job_role).permit(:title)
    end
end

app/app/helpers/job_roles_helper.rb
module JobRolesHelper
end

app/app/views/job_roles/_form.html.erb
<%= form_with(model: job_role, local: true) do |form| %>
  <% if job_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_role.errors.count, "error") %> prohibited this job_role from being saved:</h2>

      <ul>
      <% job_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_role_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/app/views/job_roles/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Cargos', job_roles_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Editar</li>
  </ol>
</nav>

<h1>Editing Job Role</h1>

<%= render 'form', job_role: @job_role %>

<%= link_to 'Show', @job_role %> |
<%= link_to 'Back', job_roles_path %>

app/app/views/job_roles/index.html.erb
<p id="notice"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Cargos</li>
  </ol>
</nav>

<h1>Job Roles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_roles.each do |job_role| %>
      <tr>
        <td><%= job_role.title %></td>
        <td><%= link_to 'Show', job_role %></td>
        <td><%= link_to 'Edit', edit_job_role_path(job_role) %></td>
        <td><%= link_to 'Destroy', job_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Role', new_job_role_path %>

app/app/views/job_roles/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Cargos', job_roles_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Novo</li>
  </ol>
</nav>

<h1>New Job Role</h1>

<%= render 'form', job_role: @job_role %>

<%= link_to 'Back', job_roles_path %>

app/app/views/job_roles/show.html.erb
<p id="notice"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Bem-Vindo', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Cargos', job_roles_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @job_role.title %></li>
  </ol>
</nav>

<p>
  <strong>Title:</strong>
  <%= @job_role.title %>
</p>

<%= link_to 'Edit', edit_job_role_path(@job_role) %> |
<%= link_to 'Back', job_roles_path %>